
node {
    try {
        notifyBuild('STARTED')
        //stage 'build'
        //  openshiftBuild bldCfg: 'gitbook-centos-docker'
        stage 'scan image'
            withCredentials([usernamePassword(credentialsId: '4eb0c46e-57cf-472f-b65a-0a69fcee5272', passwordVariable: 'password', usernameVariable: 'username')]) {
                sh '''
                docker login -e=shea.stewart@arctiq.ca -u=$username -p=$password docker.io
                '''
            }
            aqua hideBase: false, hostedImage: 'cicd/gitbook-centos-docker:latest', localImage: '', locationType: 'hosted', notCompliesCmd: '', onDisallowed: 'fail', registry: 'ocp', showNegligible: false


        stage 'ask for deployment'
            input id: 'Approve01', message: 'Looks Good! Wanna deploy?????', ok: 'HANG TIGHT!'

        stage 'deploy'
          openshiftDeploy depCfg: 'gitbook-centos-docker', verbose: 'true'

        stage 'verify'
          openshiftVerifyDeployment depCfg: 'gitbook-centos-docker', verbose: 'true', verifyReplicaCount: 'false'


  } catch (e) {
    // If there was an exception thrown, the build failed
    currentBuild.result = "FAILED"
    throw e
  } finally {
    // Success or failure, always send notifications
    notifyBuild(currentBuild.result)
  }
}

def notifyBuild(String buildStatus = 'STARTED') {
  // build status of null means successful
  buildStatus =  buildStatus ?: 'SUCCESSFUL'

  // Default values
  def colorName = 'RED'
  def colorCode = '#FF0000'
  def subject = "${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
  def summary = "${subject} (${env.BUILD_URL})"

  // Override default values based on build status
  if (buildStatus == 'STARTED') {
    color = 'YELLOW'
    colorCode = '#FFFF00'
  } else if (buildStatus == 'SUCCESSFUL') {
    color = 'GREEN'
    colorCode = '#00FF00'
  } else {
    color = 'RED'
    colorCode = '#FF0000'
  }

  // Send notifications
  slackSend (color: colorCode, message: summary)
}
